// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqi78kTENNWwADXDQTa7-ehUpWsG0hpPw',
    appId: '1:41637284140:web:decab0dc3d68f9575f8489',
    messagingSenderId: '41637284140',
    projectId: 'insta-flutter-project',
    authDomain: 'insta-flutter-project.firebaseapp.com',
    storageBucket: 'insta-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADucNY7B0ixK7kDW3BkwSLdOYrCfuF5v4',
    appId: '1:41637284140:android:88d78491554725e55f8489',
    messagingSenderId: '41637284140',
    projectId: 'insta-flutter-project',
    storageBucket: 'insta-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUd-dVXwf9PFJaKxN-YrVHMSXjJ8Maahc',
    appId: '1:41637284140:ios:68402744d4b0cf825f8489',
    messagingSenderId: '41637284140',
    projectId: 'insta-flutter-project',
    storageBucket: 'insta-flutter-project.appspot.com',
    iosClientId: '41637284140-nbsgv4lqic3cp1q9viv4plivi22k5ur8.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUd-dVXwf9PFJaKxN-YrVHMSXjJ8Maahc',
    appId: '1:41637284140:ios:68402744d4b0cf825f8489',
    messagingSenderId: '41637284140',
    projectId: 'insta-flutter-project',
    storageBucket: 'insta-flutter-project.appspot.com',
    iosClientId: '41637284140-nbsgv4lqic3cp1q9viv4plivi22k5ur8.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
